PROGRAM MASQUERADERS;
VAR
I,X,CNT1,CNT2,CNT3,CNT4,CNT5:INTEGER;
NAME:STRING;
SECT1N:ARRAY[1..15] OF STRING;
SECT2N:ARRAY[1..15] OF STRING;
SECT3N:ARRAY[1..15] OF STRING;
SECT4N:ARRAY[1..15] OF STRING;
SECT5N:ARRAY[1..15] OF STRING;
AMOT,AMOT1,AMOT2,AMOT3,AMOT4,AMOT5:integer;
TTSEC1,TTSEC2,TTSEC3,TTSEC4,TTSEC5:integer;
BEGIN
CNT1:=0;
CNT2:=0;
CNT3:=0;
CNT4:=0;
CNT5:=0;
REPEAT
BEGIN
I:=I+1;

WRITELN('PLEASE ENTER NAME');
READLN(NAME);
WRITELN('PLEASE ENTER AMOUNT PAID');
READLN(AMOT);
WRITELN('ENTER 2 TO STOP');
READLN(X);

IF AMOT=160 THEN
BEGIN
 AMOT1:=AMOT; 
 CNT1:=CNT1+1;
 SECT1N[CNT1]:=Name;
 TTSEC1:=CNT1*160;
END

ELSE

IF AMOT=220 THEN
BEGIN
 AMOT2:=AMOT;
 CNT2:=CNT2+1;
 SECT2N[CNT2]:=Name;
 TTSEC2:=CNT2*220;
END
ELSE

IF AMOT=280 THEN
BEGIN
 AMOT3:=AMOT;
 CNT3:=CNT3+1;
 SECT3N[CNT3]:=Name;
 TTSEC3:=CNT3*280;
END
ELSE
 
IF AMOT=350 THEN
BEGIN
 AMOT4:=AMOT; 
 CNT4:=CNT4+1;
 SECT4N[CNT4]:=Name;
 TTSEC4:=CNT4*350;
END
ELSE

IF AMOT=425 THEN
BEGIN
  AMOT5:=AMOT;
 CNT5:=CNT5+1;
 SECT5N[CNT5]:=Name;
 TTSEC5:=CNT5*425;
END
END;
UNTIL X=2;

 WRITELN(' ');
    WRITELN('SECTION ONE ');
    WRITELN('AMOUNT OF MASQUERADERS IN SECTION :' ,CNT1);
FOR I:=1 TO CNT1 DO
  BEGIN
    WRITELN(SECT1N[I] , ' ',AMOT1 );
    END;
    WRITELN(TTSEC1);
  WRITELN(' ');
   WRITELN('SECTION TWO ');
   WRITELN('AMOUNT OF MASQUERADERS IN SECTION :',CNT2);
FOR I:=1 TO CNT2 DO
BEGIN
 
   WRITELN(SECT2N[I], ' ',AMOT2);
   END;
   WRITELN(TTSEC2);

 WRITELN(' ');
  WRITELN('SECTION THREE ');
  WRITELN('AMOUNT OF MASQUERADERS IN SECTION :',CNT3);
FOR I:=1 TO CNT3 DO
BEGIN
 
  WRITELN(SECT3N[I], ' ',AMOT3 );
  END;
  WRITELN(TTSEC3);

 WRITELN(' ');
  WRITELN('SECTION FOUR ');
  WRITELN('AMOUNT OF MASQUERADERS IN SECTION :',CNT4);
FOR I:=1 TO CNT4 DO 
BEGIN
 
  WRITELN(SECT4N[I], ' ',AMOT4 );
  END;
  WRITELN(TTSEC4);

 WRITELN(' ');
  WRITELN('SECTION FIVE');
  WRITELN('AMOUNT OF MASQUERADERS IN SECTION :',CNT5);
FOR I:=1 TO CNT5 DO
BEGIN
 
  WRITELN(SECT5N[I], ' ',AMOT5 );
  
END;
  WRITELN(TTSEC5);


END.  
